from architecture import architecture
from assert_statement import assert_statement
from attribute import attribute
from blank import blank
from case import case
from comment import comment
from component import component
from concurrent import concurrent
from constant import constant
from entity import entity
from file_statement import file_statement
from for_loop import for_loop
from function import function
from generate import generate
from generic import generic
from if_statement import if_statement
from instantiation import instantiation
from library import library
from package_body import package_body
from package import package
from port import port
from process import process
from procedure import procedure
from sequential import sequential
from signal import signal
from subtype import subtype
from type_definition import type_definition
from variable_assignment import variable_assignment
from variable import variable
from while_loop import while_loop
from with_statement import with_statement
