from architecture import architecture
from assert_statement import assert_statement
from blank import blank
from case import case
from comment import comment
from component import component
from concurrent import concurrent
from constant import constant
from entity import entity
from forLoop import forLoop
from function import function
from generate import generate
from generic import generic
from ifStatement import ifStatement
from instantiation import instantiation
from library import library
from packageBody import packageBody
from package import package
from port import port
from process import process
from sequential import sequential
from signal import signal
from type import type
from variable_assignment import variable_assignment
from variable import variable
